from __future__ import annotations


ACTIVE_PAYMENT_MODULE_STATE_KEY = "payment_module_id"
DESIRED_MODULE_IDS_STATE_KEY = "desired_module_ids"
DESIRED_MODULE_IDS_UPDATED_AT_STATE_KEY = "desired_module_ids_updated_at"
SETUP_STARTED_AT_STATE_KEY = "setup_started_at"
SETUP_COMPLETED_AT_STATE_KEY = "setup_completed_at"
SETUP_LAST_REVIEWED_AT_STATE_KEY = "setup_last_reviewed_at"
SETUP_OPERATOR_LOCALE_STATE_KEY = "setup_operator_locale"
SETUP_HARDWARE_PROFILE_STATE_KEY = "setup_hardware_profile"
SETUP_HARDWARE_BASE_PROFILE_STATE_KEY = "setup_hardware_base_profile"
SETUP_HARDWARE_ENABLED_ADDONS_STATE_KEY = "setup_hardware_enabled_addons"
SETUP_PAYMENT_MODULE_STATE_KEY = "setup_payment_module_id"
SETUP_CATALOG_READY_STATE_KEY = "setup_catalog_ready"
SETUP_COMPLETED_STEPS_STATE_KEY = "setup_completed_steps"
SETUP_SELF_TEST_RESULTS_STATE_KEY = "setup_self_test_results"


__all__ = [
    "ACTIVE_PAYMENT_MODULE_STATE_KEY",
    "DESIRED_MODULE_IDS_STATE_KEY",
    "DESIRED_MODULE_IDS_UPDATED_AT_STATE_KEY",
    "SETUP_STARTED_AT_STATE_KEY",
    "SETUP_COMPLETED_AT_STATE_KEY",
    "SETUP_LAST_REVIEWED_AT_STATE_KEY",
    "SETUP_OPERATOR_LOCALE_STATE_KEY",
    "SETUP_HARDWARE_PROFILE_STATE_KEY",
    "SETUP_HARDWARE_BASE_PROFILE_STATE_KEY",
    "SETUP_HARDWARE_ENABLED_ADDONS_STATE_KEY",
    "SETUP_PAYMENT_MODULE_STATE_KEY",
    "SETUP_CATALOG_READY_STATE_KEY",
    "SETUP_COMPLETED_STEPS_STATE_KEY",
    "SETUP_SELF_TEST_RESULTS_STATE_KEY",
]
